sudo: false

cache:
    apt: true
    directories:
        - $HOME/.composer/cache

language: php

matrix:
    fast_finish: true
    include:
        - php: 5.6
          env: CS_FIXER=run
        - php: 7.0
        - php: 7.1
        - php: nightly
    allow_failures:
        - php: nightly

before_script:
    - composer --prefer-dist install --no-interaction -o --no-progress

script:
    - php ./bin/phpspec run --format=pretty
    - if [ "$CS_FIXER" = "run" ]; then php bin/php-cs-fixer fix --verbose --dry-run ; fi;

notification:
    email: false
